//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub mod prelude;

pub mod login_oauth_info;
pub mod logins;
pub mod media;
pub mod posts;
pub mod scopes;
pub mod user_scopes;
pub mod users;
