//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::login_oauth_info::Entity as LoginOauthInfo;
pub use super::logins::Entity as Logins;
pub use super::media::Entity as Media;
pub use super::posts::Entity as Posts;
pub use super::scopes::Entity as Scopes;
pub use super::user_scopes::Entity as UserScopes;
pub use super::users::Entity as Users;
